### PR TITLE
metrics-exporter-prometheus: Single runtime install

### LINKED ISSUE #250: [metrics-exporter-prometheus] calling `.install()` twice from inside tokio runtime panics
If you inadvertently call `PrometheusBuilder::install` twice, you should be able to swallow the error and accept the previously provided prometheus builder instance. In practice, you cannot do this. The second call to `install` panics because the single-threaded tokio runtime that is created to run the exporter is dropped from within the main tokio runtime.  

# Minimum example

```toml
tokio = { version = "1.14.0", features = ["full"] }
metrics-exporter-prometheus = "0.6.1"
```

```rust
#[tokio::main]
async fn main() {
    let _ = metrics_exporter_prometheus::PrometheusBuilder::new().install();
    let _ = metrics_exporter_prometheus::PrometheusBuilder::new().install();
}
```

Output: 

```
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:543:12
   1: tokio::runtime::blocking::shutdown::Receiver::wait
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/shutdown.rs:51:21
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/pool.rs:144:12
   3: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/pool.rs:161:9
   4: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ptr/mod.rs:188:1
   5: core::ptr::drop_in_place<tokio::runtime::Runtime>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ptr/mod.rs:188:1
   6: metrics_exporter_prometheus::builder::PrometheusBuilder::install
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/metrics-exporter-prometheus-0.6.1/src/builder.rs:227:5
   7: metrics_test_tokio::main::{{closure}}
             at ./src/main.rs:4:13
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/future/mod.rs:80:19
   9: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/park/thread.rs:263:54
  10: tokio::coop::with_budget::{{closure}}
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:106:9
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:399:16
  12: std::thread::local::LocalKey<T>::with
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/thread/local.rs:375:9
  13: tokio::coop::with_budget
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:99:5
  14: tokio::coop::budget
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:76:5
  15: tokio::park::thread::CachedParkThread::block_on
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/park/thread.rs:263:31
  16: tokio::runtime::enter::Enter::block_on
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/enter.rs:151:13
  17: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/mod.rs:77:9
  18: tokio::runtime::Runtime::block_on
             at /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/mod.rs:463:43
  19: metrics_test_tokio::main
             at ./src/main.rs:4:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
```

### PR DESCRIPTION
**Pull request by lilymara-onesignal**
Allow exporter to be installed on an existing tokio runtime when called form
within that runtime.

Fixes #250

### CODE REVIEW

**Comment by tobz** [comment]
@lilymara-onesignal Thanks for your contribution!

Overall, I'm OK with the idea of spawning the exporter into the current runtime if we're already within one, but I think the doc comment for `PrometheusBuilder::install` should be updated, at this point, to indicate that this will happen, and that if we're not within a runtime, a new single-threaded runtime will be spawned in the background.

**Comment by lilymara-onesignal** [comment]
Thanks @tobz! I updated the comment, does this seem appropriate?

File: metrics-exporter-prometheus/src/builder.rs [hunk 1]
```diff
@@ -194,7 +194,11 @@ impl PrometheusBuilder {
         self
     }
 
-    /// Builds the recorder and exporter and installs them globally.
+    /// Builds the recorder and exporter and installs them globally. Behaves
+    /// differently depending on if called from within a tokio runtime. If
+    /// called within a Runtime, spawns the handler future onto the current
+    /// runtime. If called with no active runtime, spawns a new single-threaded
+    /// tokio runtime and polls the handler future from a new background thread.
```
Comment (tobz) [inline metrics-exporter-prometheus/src/builder.rs:201]:
```suggestion
    /// Builds the recorder and exporter and installs them globally.
    ///
    /// If called from within a Tokio runtime, the handler future is spawned directly
    /// into the runtime.  Otherwise, a new single-threaded Tokio runtime is created
    /// on a background thread, and the handler is spawned there.
```

File: metrics-exporter-prometheus/src/builder.rs [hunk 2]
```diff
@@ -194,12 +194,35 @@ impl PrometheusBuilder {
...
```
Comment (tobz) [inline metrics-exporter-prometheus/src/builder.rs:201]:
```suggestion
    /// Builds the recorder and exporter and installs them globally.
    ///
    /// When called from within a Tokio runtime, the handler future is spawned directly
    /// into the runtime.  Otherwise, a new single-threaded Tokio runtime is created
    /// on a background thread, and the handler is spawned there.
```

**Review by tobz — CHANGES_REQUESTED** [review]
Suggested one small tweak just to align the "voice" of the comment as well as the formatting when rendered by `cargo doc`.

(I realize this may seem like a bit of a nit but I just didn't have the chance to commit it directly to the branch.)

**Review by tobz — APPROVED** [review]

**Comment by tobz** [comment]
@lilymara-onesignal This looks good to me, just need the tests to run/pass and I'll get it merged and released.

Thanks again for your contribution. 😄

**Comment by tobz** [comment]
Cut a new release that includes this: `metrics-exporter-prometheus@v0.7.0`.  LEt me know if there's any issues.

**Comment by lilymara-onesignal** [comment]
Thank you!
